In [2]:
import numpy as np

In [11]:
x=np.array([0,1,2,3,4,5,6,7,8])

In [7]:
type(x)

numpy.ndarray

In [13]:
x=x.reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.power(x,2)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
x*np.array([1,2,3])

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

In [19]:
x[x%2==0]*=-1
x

array([[ 0,  1, -2],
       [ 3, -4,  5],
       [-6,  7, -8]])

In [23]:
x = np.array([1, 2, 3, 4])
y = np.array([ [5, 6], [7, 8] ])
x.reshape(2,2)+y

array([[ 6,  8],
       [10, 12]])

In [33]:
grades = np.array([93, 95, 84, 100, 99, 87])
grades=grades.reshape(3,2)

In [31]:
grades = np.array([[93,  95],
                   [84, 100],
                    [99,  87]])

In [34]:
grades[:,:1]

array([[93],
       [84],
       [99]])

In [36]:
grades[0]

array([93, 95])

In [37]:
grades[2,1]

87

In [39]:
x=np.array(12)

In [40]:
x.item()

12

In [51]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]).reshape(2, 2, 2,2)
a[0,1,0,1]

5

In [76]:
b = np.array([[[ 0,  1,  2,  3],
                           [ 4,  5,  6,  7]],

                          [[ 8,  9, 10, 11],
                           [12, 13, 14, 15]],

                          [[16, 17, 18, 19],
                           [20, 21, 22, 23]]])

In [53]:
b.ndim

3

In [54]:
b.shape

(3, 2, 4)

In [56]:
b.size

24

In [57]:
b.dtype

dtype('int64')

In [58]:
b.itemsize

8

In [59]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
np.array(i**2 for i in range(5))

array(<generator object <genexpr> at 0x7fb023d3af20>, dtype=object)

In [64]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [65]:
# creating an array by sampling 10 numbers randomly from a mean-1, std-dev-5 normal distribution
np.random.normal(1, 5, 10)

array([ 1.24166718, -2.52174488,  5.86991408,  3.93202343, -6.3014119 ,
       -4.35228333,  2.56256356, -1.33862142, -2.55959525, -4.26097288])

In [66]:
np.array([1.5,3.2,4.6],dtype=int)

array([1, 3, 4])

In [69]:
np.linspace(0, 20, 100)

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [70]:
np.array([[[1]*3]*5]*2)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [72]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])

In [73]:
np.vstack([x,y])

array([[ 1,  2,  3],
       [-1, -2, -3]])

In [74]:
np.hstack([x,y])

array([ 1,  2,  3, -1, -2, -3])

In [78]:
[i for i in np.ndenumerate(b)]

[((0, 0, 0), 0),
 ((0, 0, 1), 1),
 ((0, 0, 2), 2),
 ((0, 0, 3), 3),
 ((0, 1, 0), 4),
 ((0, 1, 1), 5),
 ((0, 1, 2), 6),
 ((0, 1, 3), 7),
 ((1, 0, 0), 8),
 ((1, 0, 1), 9),
 ((1, 0, 2), 10),
 ((1, 0, 3), 11),
 ((1, 1, 0), 12),
 ((1, 1, 1), 13),
 ((1, 1, 2), 14),
 ((1, 1, 3), 15),
 ((2, 0, 0), 16),
 ((2, 0, 1), 17),
 ((2, 0, 2), 18),
 ((2, 0, 3), 19),
 ((2, 1, 0), 20),
 ((2, 1, 1), 21),
 ((2, 1, 2), 22),
 ((2, 1, 3), 23)]

In [79]:
np.sum(b)

276

In [80]:
np.sum(b,axis=1)

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26],
       [36, 38, 40, 42]])

In [100]:
x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15]])
#Take the natural-logarithm of the 1st and 3rd element in the 3rd-row of x, producing a shape-(2,) result.

In [101]:
x=x[2,::2]

In [102]:
np.log(x)

array([2.07944154, 2.30258509])

In [104]:
y=np.array([.8,1])*10

In [106]:
np.allclose(x,y)

True

In [108]:
x<10

array([ True, False])

In [118]:
#Given the 2D array:

x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15]])
#Add the four quadrants of x, producing a shape-(2, 2) output.

In [134]:
x[:2,:2]+x[:2,2:]+x[2:,:2]+x[2:,2:]

array([[20, 24],
       [36, 40]])

In [ ]:
#sequential

In [138]:
#(𝑁,𝑉,𝐻,C)
images = np.random.rand(100, 32, 32, 3)

In [139]:
#The average 32x32 RGB image. 
mean=np.mean(images,axis=0)
mean.shape


(32, 32, 3)

In [140]:
#The total sum of all the values in the array.
np.sum(images)

153721.15613219969

In [142]:
#The minimum blue value, respective to each image.
np.min(images[:,:,:,2], axis=(1,2))

array([5.45923839e-04, 7.92838254e-04, 1.17795839e-03, 1.73338196e-03,
       1.62347950e-03, 1.71406370e-03, 1.90046239e-03, 1.90139682e-04,
       1.25916937e-03, 3.79880322e-03, 7.34852612e-04, 2.79010253e-03,
       1.71501852e-03, 1.08006336e-03, 3.65566328e-03, 1.68037029e-03,
       5.34005850e-05, 6.40787810e-04, 7.22116901e-04, 3.53572196e-04,
       6.17346519e-04, 2.27950595e-03, 8.74614515e-04, 3.11312444e-03,
       1.59565358e-03, 1.42582619e-03, 5.83480166e-04, 2.09111932e-03,
       6.60210150e-04, 4.81915450e-04, 2.35795106e-03, 1.29460069e-03,
       1.56412224e-03, 4.86419064e-04, 6.60601400e-05, 2.26555227e-04,
       1.75097781e-04, 2.64183199e-04, 1.10250855e-03, 2.46705845e-03,
       3.98181159e-04, 1.53875727e-04, 2.70866425e-03, 4.23134865e-04,
       3.51560254e-04, 1.92764894e-04, 1.56462334e-05, 9.62405795e-04,
       9.88531514e-05, 1.09736291e-03, 4.23959754e-03, 2.01393102e-03,
       1.38456737e-03, 3.31455039e-04, 7.56780100e-05, 1.26409227e-03,
      

In [145]:
#The standard deviation among all the RGB values in all the images, 
#respective to each pixel position (thus you should produce a shape-(32, 32) array of values).
np.std(images,axis=(0,3)).shape

(32, 32)

In [146]:
#The maximum red-value in the top-left quadrant, respective to each image.
np.max(images[:,:16,16:,0],axis=(1,2)).shape

(100,)

In [147]:
np.arange(100) ** 2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [149]:
x = np.random.rand(5, 6, 8, 10)

In [154]:
x.mean(axis=(-2,-1)).shape

(5, 6)

In [155]:
x.min().shape

()

In [157]:
x.std(axis=(0, 1, 3)).shape

(8,)

In [158]:
np.sum(x, axis=(0, 1)).shape

(8, 10)

In [159]:
>>> x = np.array([[ 0,  1,  2,  3],
...               [ 4,  5,  6,  7],
...               [ 8,  9, 10, 11]])

In [164]:
np.broadcast_to(x,(2,3,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [165]:
#Generate a random array of 10,000 2D points using np.random.rand. 
#Compute the “center of mass” of these points, which is simply the 
#average x-coordinate and the average y-coordinate of these 10,000 
#points. Then, use broadcasting to compute the shape-(10000,2) array 
#that stores the position of the points relative to the center of mass. 
#For example, if the center of mass is (0.5,1), and the absolute position 
#of a point is (2,3), then the position of that point relative to the center
#of mass is simply  (2,3)−(0.5,1)=(1.5,2)

In [187]:
x=np.random.rand(10000,2)
x

array([[0.41082674, 0.30090926],
       [0.57779796, 0.52566521],
       [0.73739256, 0.61343587],
       ...,
       [0.8965849 , 0.70727314],
       [0.71852248, 0.78465502],
       [0.82256496, 0.63312445]])

In [188]:
mean=x.mean(axis=0) # -> array([mean_x, mean_y])
mean.shape
mean

array([0.50240071, 0.50127061])

In [189]:
new=x-mean
new.shape

(10000, 2)

In [180]:
np.array([1,2,3]).reshape(1,3,1,1)

array([[[[1]],

        [[2]],

        [[3]]]])

In [190]:
x=np.array([1,2,3])
x[np.newaxis,:,np.newaxis].shape

(1, 3, 1)

In [191]:
x = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]],

              [[12, 13, 14, 15],
               [16, 17, 18, 19],
               [20, 21, 22, 23]]])
#make rows sum to 1

In [194]:
y=1/x.sum(axis=0)

In [195]:
z=x*y
z.sum(axis=0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [184]:
#Using the sequential function np.max and broadcasting, n
#ormalize images such that the largest value within each color-channel of each image is 1.

images = np.random.rand(500, 48, 48, 3)


In [207]:
norm=images/np.max(images,axis=(1,2)).reshape(500,1,1,3)

In [208]:
np.all(norm.max(axis=(1,2))==1)

True

In [209]:
# a shape-(5, 3) array
>>> x = np.array([[ 8.54,  1.54,  8.12],
...               [ 3.13,  8.76,  5.29],
...               [ 7.73,  6.71,  1.31],
...               [ 6.44,  9.64,  8.44],
...               [ 7.27,  8.42,  5.27]])

# a shape-(6, 3) array
>>> y = np.array([[ 8.65,  0.27,  4.67],
...               [ 7.73,  7.26,  1.95],
...               [ 1.27,  7.27,  3.59],
...               [ 4.05,  5.16,  3.53],
...               [ 4.77,  6.48,  8.01],
...               [ 7.85,  6.68,  6.13]])